title: SRv6OPS Working Group
description: Operational and deployment considerations for SRv6
logo: /assets/srv6ops-logo.png  # optional, or comment it out
show_downloads: false
theme: jekyll-theme-minimal
